
seed: 0

data:
  path: "data/ESC-50-master/ESC-50-master"
  sample_rate: 8000
  train_folds: [1, 2, 3]
  val_folds: [4]
  test_folds: [5]
  batch_size: 8

model:
  base_filters: 32
  num_classes: 50
  optim:
    lr: 3e-4

trainer:
  gpus: 0
  max_epochs: 1